### ISSUE TITLE
Adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by drashti4** [mozilla/diversity#170] opened 2018-06-06 12:34 UTC
## Objective Goal: 
Add CONTRIBUTING.md for better understanding to new contributors. 

## Item list:
- [ ] How to install (If required)
- [ ] What type of skilled people we're looking for   
   - D & I speakers
   - Document & writing 
   - Research & Planning
- [ ] Some beginner friendly label (good first bug)

Do you think this is necessary for an open-source project?

**Comment by musingvirtual** [comment] 2018-06-06 16:44
Hi Drashti! Welcome to Mozilla Diversity!

I'm not quite sure whether you are asking advice for your project or whether you want to contribute one of these here.

Yes, I think this would be a great idea for an open-source project in general to help contributors get started!  If you're looking to contribute to our project, our Readme.MD covers most of this ground. Our good first bug label is "quick contribution."  We don't have too many opportunities for contributors here because a lot of our work is confidential - but if you want to let us know what kinds of things you might like to contribute, we'll try to keep you in mind :)

cheers,
Kate

**Comment by emmairwin** [comment] 2018-06-07 20:47
I think that would be great if you could start a contributing.md. 

https://mozillascience.github.io/working-open-workshop/contributing/

Feel free to ask us questions to help you build it :)

**Comment by drashti4** [comment] 2018-06-08 17:08
Just adding [https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/) for reference

**Comment by akshitac8** [comment] 2018-06-22 18:55
Hey, @emmairwin I guess @drashti4 has done quite good work on the contributing.MD file and shall I reopen the PR and add more suggestions and proceed it to completion.
And I think we can change this to a beginners guide to ease out the process. 
@drashti4  can you please make the required changes. Thank you :)

**Comment by drashti4** [comment] 2018-06-23 06:22
Hi @akshitac8 I need to add license link. Can anyone give suggest who will be consumer for this repo? and Who all will be project owners and contributors?

**Comment by emmairwin** [comment] 2018-06-27 00:21
is there a pull request I can see? I'm not sure what we're looking at adding here... thank you

**Comment by akshitac8** [comment] 2018-07-03 14:37
I am taking over this

**Comment by akshitac8** [comment] 2018-07-22 21:20
The Issue is successfully merged :)

**Closed by akshitac8** 2018-07-22 21:20 UTC
Labels: Documentation & Writing
